### ISSUE TITLE
Code coverage: misleading information

### ISSUE THREAD

**Issue by mnabialek** [sebastianbergmann/php-code-coverage#452] opened 2016-06-18 09:24 UTC
I'm running PHP 7.0.7 with Xdebug 2.4.0

PhpUnit versions:

```
composer show | grep phpunit
phpunit/php-code-coverage             2.2.4   Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator             1.4.1   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1   Simple template engine.
phpunit/php-timer                     1.0.7   Utility class for timing
phpunit/php-token-stream              1.4.8   Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       4.8.24  The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          2.3.8   Mock Object library for PHPUnit
```

Issue is like below. It's marked as 100% (what is probably correct) but when looking at file source only some lines as marked as green, so you start thinking - whether this 100% is fine or maybe somehow magically not the whole code was not executed (what is rather impossible in this case)

![marking lines](https://cloud.githubusercontent.com/assets/7656807/16170077/44821bc4-3546-11e6-9956-7877ad3b41cb.jpg)

It happens also for some other cases - for example closures.

**Comment by Rockstar04** [comment] 2016-06-28 20:28
Similar to #422

**Comment by ramsey** [comment] 2016-11-24 00:08
Maybe a duplicate of #411

**Comment by sebastianbergmann** [comment] 2017-11-26 15:51
Please open a new ticket in case this is not a duplicate of #411 or #422.

**Closed by sebastianbergmann** 2017-11-26 15:51 UTC
