### ISSUE TITLE
Coverage information say's that an ending curly is dead not covered

### ISSUE THREAD

**Issue by cmodijk** [sebastianbergmann/php-code-coverage#414] opened 2015-12-28 22:10 UTC
For this simple function the ending curly brace is detected as dead code. I think it has something to do with the finally part but i'm not sure. 

```
class Unzip
{
    public function extractFile()
    {
        try {
            return true;
        } finally {
            echo 'Do somthing';
        }
    }
}
```

<img width="346" alt="schermafbeelding 2015-12-28 om 23 06 37" src="https://cloud.githubusercontent.com/assets/771041/12026242/afeb9d84-adb7-11e5-9ded-992cbe313870.png">

The test case

```
class UnzipTest extends \PHPUnit_Framework_TestCase
{
    public function testUnzip()
    {
        $unzip = new Unzip();
        $this->assertTrue($unzip->extractFile());
    }
}
```

Versions
* Xdebug: v2.3.3
* phpunit: 4.8.21
* PHP: 5.6.16

**Comment by sebastianbergmann** [comment] 2015-12-29 07:17
Looks like an [edge case](https://phpunit.de/manual/current/en/code-coverage-analysis.html#code-coverage-analysis.edge-cases) to me. @derickr?

**Comment by derickr** [comment] 2015-12-30 15:26
Nope - it's not an edge case. It's because Xdebug doesn't understand the "FAST_CALL" opcode that is used for finally - and hence doesn't do proper branch and dead code analysis.

**Comment by derickr** [comment] 2015-12-30 15:46
See: http://bugs.xdebug.org/view.php?id=1241 - and it's also a problem with https://github.com/derickr/vld

**Comment by dereckson** [comment] 2016-01-10 02:01
The same issue occurs when a method throws an exception, like `abort` in the Laravel framework.

```lang=php
if (!$this->isLegitRequest()) {
    abort(403, 'Unauthorized action.');
}
```

Two tests hit this code block, one legit, one not legit, the final } is noted not executed.

**Comment by mindplay-dk** [comment] 2016-04-10 10:35
Upgrade to xdebug 2.4 stable fixed this issue for me.

@sebastianbergmann I think you can close this?

**Closed** 2016-04-10 11:07 UTC

**Comment by cmodijk** [comment] 2016-04-10 11:57
Not for me i just upgraded everything and still the same i created this example repo
```
git clone https://github.com/cmodijk/phpunit-fast-call-example.git
cd phpunit-fast-call-example
composer install
./vendor/bin/phpunit -c . --coverage-html=coverage
```

<img width="353" alt="schermafbeelding 2016-04-10 om 13 52 50" src="https://cloud.githubusercontent.com/assets/771041/14410004/88c5a818-ff23-11e5-8dbb-621cb4a6cef1.png">

```
php -v 

PHP 5.6.20 (cli) (built: Mar 31 2016 17:14:52) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

**Comment by derickr** [comment] 2016-04-10 16:36
@cmodijk - I can reproduce that. It's the bloody FAST_CALL/FAST_RET stuff for finally again. I'm mailing @nikic again as he's tried explaining this to me before :-)

**Comment by nikic** [comment] 2016-04-10 23:02
@derickr For FAST_CALL, add opline+1 as a possible branch target. Doesn't exactly reflect reality, but should be good enough for this purpose.

**Comment by derickr** [comment] 2016-04-11 19:50
Hey @nikic, that seems to do the trick. I'll cook up a patch soon enough.
