### ISSUE TITLE
Code lines skipped on class with magic method under PHP 7

### ISSUE THREAD

**Issue by danmichaelo** [sebastianbergmann/php-code-coverage#465] opened 2016-08-10 19:59 UTC
Having a class with three methods, one of them being the magic method `__get`;

``` php
class Hello
{
    public function world()
    {
        return 'Hello world';
    }

    public function you()
    {
        return 'Hello you';
    }

    public function __get($key)
    {
        return 'Hello ' . $key;
    }
}
```

and a test class that only covers 1 of the 3 above methods;

``` php
class HelloTest extends PHPUnit\Framework\TestCase
{
    public function testWorld()
    {
        $hello = new Hello();

        $this->assertEquals('Hello world', $hello->world());
    }
}
```

php-code-coverage reports that 1 out 1 method was covered (not 1 out of 3):

<img width="735" alt="skjermbilde 2016-08-10 kl 21 08 34" src="https://cloud.githubusercontent.com/assets/434495/17568334/a0feca88-5f43-11e6-867e-7cbeffe68910.png">

The problem only occurs on PHP 7. On PHP 5.5 and 5.6 it reports the expected 1 out of 3 covered. Here are some Travis logs:
- [PHP 5.5.21 with Xdebug 2.2.7](https://travis-ci.org/danmichaelo/coverage-test/jobs/151315032) works
- [PHP 5.6.5 with Xdebug 2.2.7](https://travis-ci.org/danmichaelo/coverage-test/jobs/151315033) works
- [PHP 7.0.9 with Xdebug v2.4.0](https://travis-ci.org/danmichaelo/coverage-test/builds/151312033) fails
- [PHP 7.1.0-dev with Xdebug v2.5.0-dev](https://travis-ci.org/danmichaelo/coverage-test/jobs/151315051) fails

Also, if I remove the `__get` method from the class, the report gives the expected result on PHP 7 (1 out of 2 covered), so it seems to be somehow related to that.

[Git repo for the example](https://github.com/danmichaelo/coverage-test)

Possibly related: #411 #422

**Comment by sebastianbergmann** [comment] 2016-08-11 05:17
Looks like an Xdebug issue to me. @derickr?

**Comment by GrahamCampbell** [comment] 2016-08-11 08:07
How about xdebug 2.4.1?

**Comment by derickr** [comment] 2016-08-15 09:00
Yes - please try Xdebug 2.4.1 first.

**Comment by MattiaMari** [comment] 2016-09-14 13:15
Also happens with the following configuration:
php-code-coverage 4.0.1 using PHP 7.0.10-1 with Xdebug 2.4.1 and PHPUnit 5.5.0
@derickr

**Comment by hayzem** [comment] 2016-09-27 11:31
Code line skipped with this  configuration too 
*php-code-coverage** 4.0.1 using PHP 7.0.7-1~dotdeb+8.1 with Xdebug 2.4.1 and PHPUnit 5.5.5*

**Comment by zanematthew** [comment] 2016-10-15 03:02
Same

`Generated by php-code-coverage 4.0.1 using PHP 7.0.9-1+deb.sury.org~trusty+1 with Xdebug 2.4.0 and PHPUnit 5.6.1 at Sat Oct 15 2:51:54 UTC 2016.`

**Comment by zanematthew** [comment] 2016-10-15 03:36
FYI, just updated to xdebug 2.4.1

`Generated by php-code-coverage 4.0.1 using PHP 7.0.9-1+deb.sury.org~trusty+1 with Xdebug 2.4.1 and PHPUnit 5.6.1 at Sat Oct 15 3:35:08 UTC 2016.`

**Comment by ramsey** [comment] 2016-11-24 00:10
Possible duplicate of #411.

**Comment by sebastianbergmann** [comment] 2017-11-26 15:49
Please open a new ticket in case this is not a duplicate of #411.

**Closed by sebastianbergmann** 2017-11-26 15:49 UTC
Labels: xdebug
