### ISSUE TITLE
Count function waring for PHP 7.2

### ISSUE THREAD

**Issue by peter279k** [sebastianbergmann/php-code-coverage#583] opened 2018-02-01 15:21 UTC
PHPUnit version: ```6.4.4```.
php-code-coverage version: ```5.2.2```.

# Issue description
As title, the ```count``` function has the new feature in PHP ```7.2```.
The ```count``` function will output ```Parameter must be an array or an object that implements Countable``` if the parameter is not the ```array``` or ```countable``` type.

It should be fixed after the new version is released.
Here is the [Travis build log](https://travis-ci.org/pascaldevink/shortuuid/jobs/335614983) that output this warning during generating the code coverage report.

Thanks.

**Comment by sebastianbergmann** [comment] 2018-02-01 15:24
Duplicate of #551.

**Closed by sebastianbergmann** 2018-02-01 15:24 UTC
