### ISSUE TITLE
9.2.21 upgrade - Call to undefined method RawCodeCoverageData::markExecutableLineByBranch()

### ISSUE THREAD

**Issue by benr77** [sebastianbergmann/php-code-coverage#968] opened 2022-12-15 17:25 UTC
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.21
| PHP version               | 8.1
| Installation Method       | Composer
| Usage Method              | Symfony PHPUnit Bridge
| PHPUnit version (if used) | 9.5.27

In my project, using the Symfony PHPUnit bridge, my builds started failing without any changes to the app itself.

It turns out that the bridge was installing PHPUnit each time, but now it was using `phpunit/php-code-coverage (9.2.21)` instead of `phpunit/php-code-coverage (9.2.20)` as previously. This appears to be the only change in the build.

With version `9.2.21` I get the following error before any tests are actually run:

```
PHPUnit 9.5.27 by Sebastian Bergmann and contributors.

Testing 
Call to undefined method SebastianBergmann\CodeCoverage\RawCodeCoverageData::markExecutableLineByBranch()
```

Thanks

**Comment by sebastianbergmann** [comment] 2022-12-15 18:27
Duplicate of #966.

**Closed by sebastianbergmann** 2022-12-15 18:27 UTC
