### ISSUE TITLE
Incorrect code coverage. 

### ISSUE THREAD

**Issue by wcatron** [sebastianbergmann/php-code-coverage#471] opened 2016-09-12 15:43 UTC
I can't determine the situation that is causing this but in my project [wcatron/ionic-cloud-sdk-php](https://github.com/wcatron/ionic-cloud-sdk-php) I have a class [HttpHandler](https://github.com/wcatron/ionic-cloud-sdk-php/blob/master/src/Helpers/HttpHandler.php) which has a test class [HttpHandlerTest](https://github.com/wcatron/ionic-cloud-sdk-php/blob/master/tests/Helpers/HttpHandlerTest.php) which simply tests the constructor. When I generate the coverage it has 0% coverage for my class. When I run the tests using the debugger I step right through the constructor.

I understand the title is vague but I'm completely lost as to the context of the problem. I'll try to remember to change it if we identify the root problem.

My apologizes for posting this in the wrong place originally.

**Comment by belanur** [comment] 2016-10-26 10:20
Hi @wcatron, is this still valid? 

I cannot reproduce your issue by cloning the repository and running the tests (I tried the current stable version of PHPUnit as well as the version defined in your `composer.json`). The coverage is 100% in the HTML report.

**Comment by sebastianbergmann** [comment] 2017-11-26 15:45
No feedback, closing.

**Closed by sebastianbergmann** 2017-11-26 15:45 UTC
