### ISSUE TITLE
PHPUnit coverage reports not working properly on unset()

### ISSUE THREAD

**Issue by erayalakese** [sebastianbergmann/php-code-coverage#429] opened 2016-04-12 00:16 UTC
I'm trying to cover this code:

```
unset(
            $data['type'],
            $data['parentCompany'],
            $data['accountManager'],
            );
```

and sending this `$data` array

```
$data = [
    "name" => "x",
    "parentCompany"  => "x",
];
```

But in coverage report it's covering only `$data['type'],`line of unset() not covering other lines.

PHPUnit 5.1.2
PHP 5.6.18 with Xdebug 2.3.3

**Comment by sebastianbergmann** [comment] 2016-04-12 05:56
Does the problem still exist in PHPUnit 5.3?

**Comment by erayalakese** [comment] 2016-04-13 15:18
Yes it still exist, just tried with these:

```
PHPUnit 5.3.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 5.6.18 with Xdebug 2.3.3
```

@sebastianbergmann

**Comment by sebastianbergmann** [comment] 2016-04-20 15:15
Looks like an Xdebug issue to me. @derickr?

**Comment by derickr** [comment] 2016-04-20 15:59
Not sure, I need a full test case and script.

**Comment by sebastianbergmann** [comment] 2017-11-26 15:52
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

**Comment by sebastianbergmann** [comment] 2017-12-07 05:11
No feedback, closing.

**Closed by sebastianbergmann** 2017-12-07 05:11 UTC
Labels: bug, waiting-for-feedback, waiting-for-reproducing-example
