### ISSUE TITLE
Coverage considers closing curly brackets as "Not Executed"

### ISSUE THREAD

**Issue by maximechagnolleau** [sebastianbergmann/php-code-coverage#852] opened 2021-03-10 15:04 UTC
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.2.5
| PHP version               | 8.0.1
| Driver                    | Xdebug
| Xdebug version (if used)  | 3.0.3

![test_coverage](https://user-images.githubusercontent.com/6151180/110649260-ba550900-81b9-11eb-8aab-8668f2b652e8.png)

This closing bracket should rather be considered as:

1) "Dead code", like the opening one,
2) Or maybe "Executed".

**Comment by sebastianbergmann** [comment] 2021-03-10 15:05
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

**Comment by Titou44** [comment] 2021-03-11 08:07
Hello,
First of all, thank you for your feedback!
Here is a sample repository to reproduce the issue don't hesitate if you need any further information.
https://github.com/Titou44/coverageTest

**Comment by sebastianbergmann** [comment] 2021-03-11 08:11
Please reduce your example to only use PHPUnit and php-code-coverage. Although unlikely, I would like to exclude Behat as a problem source here.

**Comment by Titou44** [comment] 2021-03-11 08:29
Thank you, I tried to reproduce with phpunit and code coverage only but even with different attempts I didn't succeed.
There is a high chance it comes from behat, I'll open an issue on behat and I'll link the issue here.

**Comment by ciaranmcnulty** [comment] 2021-03-11 09:45
I've sent a PR that removes Behat from the reproducing repository but the issue is still there
https://github.com/Titou44/coverageTest/pull/1/files

It may be to do with how the library is being used; I don't know the API too well and I kept the code as-is, just put it in a flat file in the order Behat would execute it

**Comment by Titou44** [comment] 2021-03-11 10:28
Thank you @ciaranmcnulty.
@sebastianbergmann @derickr I merged the code that reproduces the error without behat.
Thank you in advance for your feedback.
I remain available for more information.

**Comment by dvdoug** [comment] 2021-03-11 17:12
Xdebug seems to think there really is an executable line there (maybe an implicit return?). Adding `$driver->enableDeadCodeDetection();` to the setup script changes it to show as dead rather than just uncovered.

**Comment by derickr** [comment] 2021-03-11 17:45
Every function in PHP has an implicit `return NULL;`, so yes, that exists.

**Comment by maximechagnolleau** [comment] 2021-03-11 17:49
> Xdebug seems to think there really is an executable line there (maybe an implicit return?). Adding `$driver->enableDeadCodeDetection();` to the setup script changes it to show as dead rather than just uncovered.

Sounds like a good lead. i'll try and let you know

**Comment by ciaranmcnulty** [comment] 2021-03-11 18:03
Just to note, I reproduced the issue with a slightly older xdebug

```
PHP 8.0.3 (cli) (built: Mar  4 2021 12:29:50) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Xdebug v3.0.2, Copyright (c) 2002-2021, by Derick Rethans
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies
```

On ARM MacOS, just in case that's relevant

**Comment by sebastianbergmann** [comment] 2021-03-11 18:11
This does not look like a bug in this library to me.

**Comment by Titou44** [comment] 2021-03-12 07:58
Thank you @dvdoug for the pointer!
Adding `$driver->enableDeadCodeDetection();` solves our coverage issue.
So it's a matter of configuration and not a bug.
Thank you all for your support, have a great day.

**Closed** 2021-03-12 08:01 UTC
Labels: xdebug

**Comment by maximechagnolleau** [comment] 2021-03-12 08:12
@dvdoug : works like a charm! Thank you all :)

**Comment by donquixote** [comment] 2021-11-11 00:52
@Titou44 
> Adding `$driver->enableDeadCodeDetection();` solves our coverage issue.

This is interesting.
But where would I put this code?
I run the coverage report from PhpStorm, I think this is equivalent to running `phpunit --coverage-clover=clover.xml`.
I notice that https://github.com/sebastianbergmann/php-code-coverage/blob/master/README.md asks me to put some code somewhere, but I don't get where I would put this if I want to run it like mentioned above.

**Comment by Titou44** [comment] 2021-11-16 17:41
@donquixote 
[Here](https://github.com/Titou44/coverageTest/blob/main/coverage.php) is the repository for this issue fix
