### ISSUE TITLE
Test Failure on PHP 8

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/php-code-coverage#781] opened 2020-07-24 06:51 UTC
The `SebastianBergmann\CodeCoverage\Report\Html\HtmlTest::testForFileWithIgnoredLines()` test fails on PHP 8:

```
1) SebastianBergmann\CodeCoverage\Report\Html\HtmlTest::testForFileWithIgnoredLines
source_with_ignore.php.html not match
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
       </tr>
 
       <tr>
-       <td class="">Foo</td>
+       <td class="success">Foo</td>
+       <td class="success big">       <div class="progress">
+         <div class="progress-bar bg-success" role="progressbar" aria-valuenow="100.00" aria-valuemin="0" aria-valuemax="100" style="width: 100.00%">
+           <span class="sr-only">100.00% covered (success)</span>
+         </div>
+       </div>
+</td>
+       <td class="success small"><div align="right">100.00%</div></td>
+       <td class="success small"><div align="right">n/a&nbsp;/&nbsp;n/a</div></td>
        <td class=" big"></td>
        <td class=" small"><div align="right">n/a</div></td>
        <td class=" small"><div align="right">0&nbsp;/&nbsp;0</div></td>
-       <td class=" big"></td>
-       <td class=" small"><div align="right">n/a</div></td>
-       <td class=" small"><div align="right">0&nbsp;/&nbsp;0</div></td>
        <td class=" small">1</td>
        <td class=" big"></td>
        <td class=" small"><div align="right">n/a</div></td>
@@ @@
       </tr>
 
       <tr>
-       <td class="">Bar</td>
+       <td class="success">Bar</td>
+       <td class="success big">       <div class="progress">
+         <div class="progress-bar bg-success" role="progressbar" aria-valuenow="100.00" aria-valuemin="0" aria-valuemax="100" style="width: 100.00%">
+           <span class="sr-only">100.00% covered (success)</span>
+         </div>
+       </div>
+</td>
+       <td class="success small"><div align="right">100.00%</div></td>
+       <td class="success small"><div align="right">n/a&nbsp;/&nbsp;n/a</div></td>
        <td class=" big"></td>
        <td class=" small"><div align="right">n/a</div></td>
        <td class=" small"><div align="right">0&nbsp;/&nbsp;0</div></td>
-       <td class=" big"></td>
-       <td class=" small"><div align="right">n/a</div></td>
-       <td class=" small"><div align="right">0&nbsp;/&nbsp;0</div></td>
        <td class=" small">1</td>
        <td class=" big"></td>
        <td class=" small"><div align="right">n/a</div></td>
@@ @@
     <h4>Legend</h4>
     <p><span class="success"><strong>Executed</strong></span><span class="danger"><strong>Not Executed</strong></span><span class="warning"><strong>Dead Code</strong></span></p>
     <p>
-     <small>Generated by <a href="https://github.com/sebastianbergmann/php-code-coverage" target="_top">php-code-coverage %s</a> using <a href="%s" target="_top">%s</a> at %s.</small>
+     <small>Generated by <a href="https://github.com/sebastianbergmann/php-code-coverage" target="_top">php-code-coverage 9.0-gf1741b9</a> using <a href="https://secure.php.net/" target="_top">PHP 8.0.0-dev</a> with <a href="https://xdebug.org/">Xdebug 3.0.0-dev</a> at Fri Jul 24 6:51:14 UTC 2020.</small>
     </p>
     <a title="Back to the top" id="toplink" href="#">
         <svg xmlns="http://www.w3.org/2000/svg" width="12" height="16" viewBox="0 0 12 16"><path fill-rule="evenodd" d="M12 11L6 5l-6 6h12z"/></svg>

/usr/local/src/php-code-coverage/tests/tests/HtmlTest.php:102
/usr/local/src/php-code-coverage/tests/tests/HtmlTest.php:66
```

**Comment by sebastianbergmann** [comment] 2020-07-24 06:52
@dvdoug Do you have an idea what might be going on here? Thanks!

**Comment by dvdoug** [comment] 2020-07-24 12:22
Sure, I'll take a look

**Comment by dvdoug** [comment] 2020-07-24 17:55
I can't reproduce on alpha3, so looking at the list of changes that have landed in php-src since then I suspect https://wiki.php.net/rfc/string_to_number_comparison is the cause.

I will start throwing `var_dump()`s at CI to figure out more

**Comment by dvdoug** [comment] 2020-07-24 18:19
Theory confirmed, PR coming shortly

**Comment by sebastianbergmann** [comment] 2020-07-25 04:55
Thanks!

**Closed** 2020-07-25 04:55 UTC
Labels: bug
