### ISSUE TITLE
phpunit 5 with php7 and xdebug 2.4.0RC3-dev coverage always 100% 

### ISSUE THREAD

**Issue by samsonasik** [sebastianbergmann/php-code-coverage#411] opened 2015-12-10 08:34 UTC
in favor of https://github.com/sebastianbergmann/phpunit/issues/1996#issuecomment-163517749.

**Comment by samsonasik** [comment] 2015-12-11 18:56
This is show the code line is blank/white:

![rep](https://cloud.githubusercontent.com/assets/459648/11752466/4fc3a0de-a072-11e5-9a96-8370ecc3f315.png)

And the bar coverage show green:

![green](https://cloud.githubusercontent.com/assets/459648/11752469/55ad272c-a072-11e5-8d1e-e47cf94f30bb.png)

I dug for this, found that @runInSeparateProcess in every test make works, but wondering why it need that as the tests covered only factory and using fake object, and in php 5.6, it just works without @runInSeparateProcess.

**Comment by samsonasik** [comment] 2015-12-16 17:20
I've gotten reproduce-able case for it, I tried mock SplFileObject in one of my test:

```php
$this->getMock(\SplFileObject::class, [], ['php://memory']);
```

Interestingly, this issue is only happen when using php7.

**Comment by Jean85** [comment] 2016-01-22 10:14
The README.md as of now states that PHPDbg is the only source of raw code coverage for PHP 7. Maybe that's the issue? Or the readme is not updated?

**Comment by sebastianbergmann** [comment] 2016-01-22 10:37
The documentation will be updated when Xdebug has a stable release that supports PHP 7.

**Comment by paolomainardi** [comment] 2016-01-25 22:56
I confirm the very same problem, no coverage at all but stil see 100%, with php 7.0.2 and xdebug-2.4.0RC3, from what i can understand is used in place of that.

Anyway, find attached the Dockerfile to rebuild the environment, apache+php+xdebug.

```
FROM php:7.0.2-apache
MAINTAINER paolo.mainardi@sparkfabrik.com
ENV DEBIAN_FRONTEND noninteractive

# Enable apache rewrite.
RUN a2enmod rewrite proxy proxy_http

# Install php packages.
ENV MEMCACHE_PHP7_COMMIT 7ac4e83c6cf4aa8e16f8088534096293ee8e254d
RUN apt-get update \ 
  && apt-get install -y \
  curl \
  supervisor \
  mysql-client \
  libpng12-dev \
  libjpeg-dev \
  libmemcached-dev \
  libmemcached11 \
  libxml2-dev \
  ruby \
  ruby2.1 \
  ruby2.1-dev\
  git \
  unzip \
  && gem install bundler \
  && pecl install xdebug-2.4.0RC3 \
  && git clone https://github.com/php-memcached-dev/php-memcached /usr/src/php/ext/memcached \
  && cd /usr/src/php/ext/memcached && git checkout -b php7 $MEMCACHE_PHP7_COMMIT \
  && docker-php-ext-configure memcached \
  && docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
  && docker-php-ext-install soap gd mbstring pdo pdo_mysql zip memcached \
  && apt-get autoremove -y \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
  
# Install composer, drush and tools. 
ENV DRUSH_VERSION 8.0.2
ENV VAR_DUMPER_VERSION 3.0.1
ENV COMPOSER_HOME /composer-libs
RUN mkdir /composer-libs \
    && curl -sS https://getcomposer.org/installer | php \ 
    && mv composer.phar /usr/local/bin/composer \
    && composer global require symfony/var-dumper:$VAR_DUMPER_VERSION \
    && curl -fSL "https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar" -o /usr/bin/phpcbf \
    && chmod +x  /usr/bin/phpcbf \
    && chown -R www-data:www-data /composer-libs \
    && curl -fSL "https://github.com/drush-ops/drush/releases/download/$DRUSH_VERSION/drush.phar" -o /usr/bin/drush \
    && chmod +x /usr/bin/drush \
    && drush @none dl drush_language-7.x-1.5
  
## Configure PHP and Apache and supervisord.
RUN echo "zend_extension=opcache.so" >> "/usr/local/etc/php/conf.d/ext-opcache.ini" && \
    echo "opcache.enable_cli=0" >> "/usr/local/etc/php/conf.d/ext-opcache.ini" && \
    echo "opcache.memory_consumption=128" >> "/usr/local/etc/php/conf.d/ext-opcache.ini" && \
    echo "opcache.interned_strings_buffer=8" >> "/usr/local/etc/php/conf.d/ext-opcache.ini" && \
    echo "opcache.max_accelerated_files=100000" >> "/usr/local/etc/php/conf.d/ext-opcache.ini" && \
    echo "opcache.use_cwd=1" >> "/usr/local/etc/php/conf.d/ext-opcache.ini" && \
    echo "opcache.fast_shutdown=1" >> "/usr/local/etc/php/conf.d/ext-opcache.ini" && \
    echo "realpath_cache_size=2M" >> "/usr/local/etc/php/conf.d/docker.ini" && \
    echo "memory_limit=2048M" >> "/usr/local/etc/php/conf.d/docker.ini" && \
    echo "auto_prepend_file = /composer-libs/vendor/autoload.php" >> "/usr/local/etc/php/conf.d/docker.ini" && \
    echo "date.timezone=Europe/Rome" >> "/usr/local/etc/php/conf.d/timezone.ini" && \
    # this is an hack to enable xdebug just for apache by default.
    docker-php-ext-enable xdebug && \
    mkdir -p /usr/local/etc/php/apache2 && \
    cp -R /usr/local/etc/php/conf.d /usr/local/etc/php/apache2 && \
    rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    echo 'export PHP_INI_SCAN_DIR=/usr/local/etc/php/apache2/conf.d' >> /etc/apache2/envvars && \
    echo "ProxyPass /http-bind http://openfire:7070/http-bind/ connectiontimeout=5 timeout=30" >> "/etc/apache2/apache2.conf" && \
    echo "ProxyPassReverse /http-bind http://openfire:7070/http-bind/" >> "/etc/apache2/apache2.conf" && \
    echo 'ErrorLog /dev/stdout\n' >> /etc/apache2/apache2.conf && \
    echo 'CustomLog /dev/stdout combined\n' >> /etc/apache2/apache2.conf && \
    echo '[program:apache2]\ncommand=/bin/bash -c "source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND"\nautorestart=true\nstdout_logfile=/dev/stdout\nstdout_logfile_maxbytes=0\n' >> /etc/supervisor/supervisord.conf && \
    echo "export TERM=xterm" >> /etc/bash.bashrc

# Copy application.
COPY . /var/www/html/

# Expose apache 
EXPOSE 80 

# Execute daemons.
CMD exec supervisord -n
```

**Comment by Engerim** [comment] 2016-02-01 19:30
With xdebug-2.4.0RC4 seems the code coverage correct

**Comment by samsonasik** [comment] 2016-02-01 21:03
@Engerim RC4 still not work in mine

**Comment by asgrim** [comment] 2016-02-12 12:04
It's worth pointing out that this was also reported in https://bugs.xdebug.org/view.php?id=1224 (with steps to reproduce using @ramsey's uuid-doctrine library), but it was found not to be an issue in Xdebug.

**Comment by sebastianbergmann** [comment] 2016-02-12 12:15
Give me a minimal, self-contained, reproducing test case and I will try to debug your issue. I can only say that I cannot reproduce this with any of my projects with PHP 7.0.3 and Xdebug 2.4.0RC4.

**Comment by asgrim** [comment] 2016-02-12 13:03
I already linked to it, but here is the steps anyway (with the correct commit as mentioned in the Xdebug bug report):

> I'm experiencing the same issue with PHP 7.0.0 and Xdebug v2.4.0RC3. Here are the steps to reproduce:
> 
> ```
> git clone https://github.com/ramsey/uuid-doctrine.git
> cd uuid-doctrine/
> git checkout abbcbe56b023319dea7a72177333089cf47f5a69
> composer install
> ./vendor/bin/phpunit --verbose --coverage-html build/coverage
> ```
>
> Open build/coverage/index.html. Click on UuidBinaryType.php and look at around lines 50-52, which should look like this:
> 
> ```
> return $platform->getBlobTypeDeclarationSQL([
>     'length' => '16',
> ]);
> ```

**Comment by guenti** [comment] 2016-02-12 13:21
Same issue here:
PHP 7.0.2 with Xdebug v2.4.0RC4

**Comment by sebastianbergmann** [comment] 2016-02-12 13:22
@asgrim Sorry, but that is not really "minimal, self-contained". I'll try anyway but not before next week.

**Comment by asgrim** [comment] 2016-02-12 13:31
@sebastianbergmann it's pretty minimal, the whole library consists of two src classes, and two test classes :)

**Comment by sebastianbergmann** [comment] 2016-02-12 14:18
Okay, now I understand what this report is about.

![screenshot from 2016-02-12 09-12-55](https://cloud.githubusercontent.com/assets/25218/13009175/e9f95398-d168-11e5-901a-a8b81661e3a2.png)

I thought that you were not getting any code coverage at all.

**Comment by ramsey** [comment] 2016-02-12 14:44
Thanks, @asgrim, for letting @sebastianbergmann know about this issue. I discussed it yesterday with @derickr, and it was clear I was going to need to open an issue over here about it. :-)

Sebastian, it's difficult to make a very minimal example, since it doesn't seem to be the actual code itself that is the problem. Derick's note here seems applicable: https://bugs.xdebug.org/view.php?id=1224#c3481

**Comment by kegi** [comment] 2016-02-13 16:40
I'm running xdebug 2.4.0RC4 and I'm not able to run the code coverage at all : "No whitelist configured, no code coverage will be generated", the same behaviour as if xdebug was missing. Am I missing something ?

**Comment by sebastianbergmann** [comment] 2016-02-13 16:44
Yes, you are missing the fact that configuring a whitelist is required.

**Comment by ramsey** [comment] 2016-02-13 17:21
@kegi, see https://phpunit.de/manual/current/en/code-coverage-analysis.html#code-coverage-analysis.whitelisting-files

**Comment by raziel057** [comment] 2016-02-15 15:52
I confirm the issue with the following configuration:
PHP_CodeCoverage 3.2.0 using PHP 7.0.0-5+deb.sury.org~trusty+1 and PHPUnit 5.2.5

```
PHP 7.0.0-5+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0RC4, Copyright (c) 2002-2016, by Derick Rethans
```

![code-coverage](https://cloud.githubusercontent.com/assets/652505/13053364/67ab7602-d404-11e5-8909-2472b9580344.png)

**Comment by sebastianbergmann** [comment] 2016-02-15 15:55
@raziel057 What you report is something completely different from what @ramsey is reporting.

What is shown in your screenshot, @raziel057, could be correct in case that file is not loaded / executed at all while the tests are running, for instance. Anyway, this should be in a separate ticket with a minimal, self-contained, reproducing example.

**Comment by raziel057** [comment] 2016-02-15 16:23
The code is not executed at all but the coverage is 100%, so for me it's a problem. 
I don't understand why it's different to the original issue of this ticket.
I will try to provide a minimal example in another ticket...

**Comment by sebastianbergmann** [comment] 2016-02-15 16:26
@raziel057 Again: it's a separate issue. And a cosmetic one. 0 executable lines are executed -> 0/0 -> 100%. If you have better idea of representing this information: please open a separate ticket. Thanks!

**Comment by paolomainardi** [comment] 2016-02-15 17:27
@sebastianbergmann sorry but that `0/0 -> 100% coverage` appear to me just like an error and not a cosmetic issue.

**Comment by sebastianbergmann** [comment] 2016-02-15 17:33
@paolomainardi Cosmetic or not, it is something different than is discussed in this issue. Please open a separate issue for if you care about it so deeply.

**Comment by paolomainardi** [comment] 2016-02-15 17:40
@sebastianbergmann i'm not really sure that is something different from the original issue, we have different behaviours running the same suite just switching php version from 5 to 7, for example showing 100% coverage.

**Comment by Jean85** [comment] 2016-02-15 17:44
@paolomainardi this is not the same. If you look above, @sebastianbergmann posted a screenshot with covered lines highlighted as covered, where there should be none, and 0/0 should be a correct behaviour. The 0/0 -> 100% is, instead, the cosmetic issue.

**Comment by ramsey** [comment] 2016-02-15 17:45
On PHP 5.6, @raziel057's code would show up as red and untested, even if it wasn't executed, and the coverage would not show 100%. I think it's the same (or related).

**Comment by ramsey** [comment] 2016-02-15 17:50
@Jean85 In the screenshot @sebastianbergmann posted earlier, the green lines are correct. What are incorrect are the lines below the green lines. In PHP 5.6, this same coverage report shows the following, which is how I expect it to look:

![code-coverage](https://cloud.githubusercontent.com/assets/42941/13056313/4019730c-d3da-11e5-830b-65f27b0e2de3.png)

**Comment by derickr** [comment] 2016-02-15 17:58
It's not a renderer issue. If I remove some tests, then the lines would sometimes appear as they should be. I think some data actually gets thrown away somewhere.

**Comment by sebastianbergmann** [comment] 2016-02-15 19:44
Thanks, @derickr.

**Comment by AngeIII** [comment] 2016-04-19 07:44
It seems problem is not fixed yet?

**Comment by rsahai91** [comment] 2016-05-06 02:07
I'm seeing the same issue in which a file reports 100% code coverage, shows green lines for code that **is** tested, but shows white for the rest of the file (where it should show red, and is executable code). Any fixes or suggested work arounds? Even before i wrote any tests for the file it showed up as 100%.

**Comment by samsonasik** [comment] 2016-05-06 05:52
the workaround is using processIsolation=true in your phpunit.xml

**Comment by tivnet** [comment] 2016-05-10 04:24
@samsonasik Thank you for the workaround!

I was getting the `Process finished with exit code -1073741819 (0xC0000005)` error, and had to switch back to PHP 5.6

With `processIsolation="true"`, PHP7 does not fail.

**Comment by ramsey** [comment] 2016-05-10 13:48
> I was getting the Process finished with exit code -1073741819 (0xC0000005) error, and had to switch back to PHP 5.6

@tivnet, I think this is a different issue than what is reported in this thread. You might want to open another issue to capture and track that.

As for the use of `processIsolation="true"`, I can confirm that it does fix the issue for me. You can test it on my ramsey/uuid-doctrine library using the instructions posted in @asgrim's [Feb 12 comment](https://github.com/sebastianbergmann/php-code-coverage/issues/411#issuecomment-183316540) on this thread.

Using `processIsolation="true"` is, as @tivnet said, very slow.

**Comment by mauryfs** [comment] 2016-05-11 17:44
Here is another self contained example. I have a suspicion it has something to do with registering a custom autoloader in the boostrap:
```php
<?php
	class Highlight
	{
		protected $highlight;

		public function __construct()
		{
			$this->highlight = 'abstract';
		}
	}
```
```php
<?php
	class HighlightGood extends Highlight
	{
		public function __construct()
		{
			$this->highlight = 'good';
		}

		public function getTrue()
		{
			return true;
		}

		public function getFalse()
		{
			return false;
		}
	}
```
```php
<?php
	class HighlightBad extends Highlight
	{
		public function __construct()
		{
			$this->highlight = 'bad';
		}

		public function getTrue()
		{
			return true;
		}

		public function getFalse()
		{
			return false;
		}
	}
```
```php
<?php
	class HighLightLoadingTest extends PHPUnit_Framework_TestCase
	{
		public function testLoadHighlightGood()
		{
			$test = new HighlightGood;
			$this->assertTrue($test->getTrue());
		}
		public function testLoadHighlightBad()
		{
			$test = new HighlightBad;
			$this->assertTrue($test->getTrue());
		}
	}
```
```php
<?php
	require_once('vendor/autoload.php');

	spl_autoload_register(function ($class) {
		if(substr($class, 0, 9) == 'Highlight')
		{
			require_once('core/highlight/'.$class.'.php.inc');
		}
	});
?>
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit bootstrap="bootstrap.php"
		 backupGlobals="false"
		 colors="true"
		 processIsolation="false">

	<testsuites>
		<testsuite name="Hightlight Test">
			<directory suffix="Test.php">highlight</directory>
		</testsuite>
	</testsuites>

	<filter>
		<whitelist addUncoveredFilesFromWhitelist="true" processUncoveredFilesFromWhitelist="true">
			<directory suffix=".php.inc">../core/highlight</directory>
		</whitelist>
	</filter>

	<logging>
		<log type="coverage-html" target="../build/reports/coverage"/>
	</logging>
</phpunit>
```
```
c:\inetpub\wwwroot>phpunit --configuration=tests/phpunit_highlight.xml
PHPUnit 5.3.2 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

Time: 154 ms, Memory: 4.00Mb

OK (2 tests, 2 assertions)

Generating code coverage report in HTML format ... done
```
Here are the expected results in PHP5.6.21 with xdebug-2.4.0-5.6-vc11-nts-x86_64.dll
![php5](https://cloud.githubusercontent.com/assets/2272086/15189618/fdc98a00-1768-11e6-8175-f6020fa60b56.png)

Here are the unexpected results in PHP7.0.6 with xdebug-2.4.0-7.0-vc14-nts-x86_64.dll. Oddly, only HighlightBad.php.inc has incorrect highlighting on line 16.
![php7](https://cloud.githubusercontent.com/assets/2272086/15189637/130717de-1769-11e6-9bc1-c3162b6fa148.png)

I can aslo confirmed setting processIsolation="true" does fix the problem, but is not a desirable solution.

**Comment by xsuchy09** [comment] 2016-05-20 08:22
Same issue here:
PHP 7.0.6-13+donate.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans

PHPUnit 5.3.4 by Sebastian Bergmann and contributors.

**Comment by renegat59** [comment] 2016-05-28 13:04
Confirming the same issue:
PHP 7.0.4-7ubuntu2.1 (cli) ( NTS )
PHPUnit 5.1.3 
CodeCoverage 3.2.1+dfsg-1
PHP XDebug 2.4.0-1

Any class that has at least one test written displays in coverage report as 100% covered (both in Netbeans and in HTML output). Example screenshots:

![function](https://cloud.githubusercontent.com/assets/2337858/15627460/0c61a49c-24e5-11e6-8d47-19b810ca4086.png)

![coverage](https://cloud.githubusercontent.com/assets/2337858/15627464/23c5f07a-24e5-11e6-8148-c6d620125efb.png)

I understand the explanation the 0/0 is 100%, but this method has 3 lines. In short words, I never get any red lines in my coverage report. It's always either green or white and the coverage is always 100%. using `processIsolation` did not work for me.

**Comment by Thijmen** [comment] 2016-06-29 12:07
Still facing this problem.

**Comment by tmey2016** [comment] 2016-07-02 02:44
I faced this issue with xdebug and phpdbg in php 7. Upgrading php to 7.0.8 resolved this issue completely.

**Comment by Thijmen** [comment] 2016-07-03 16:27
I upgraded to PHPUnit 5.4.6 and PHP 7.0.8 and processIsolation=true and I get a working code coverage. 😄

**Comment by samsonasik** [comment] 2016-07-03 22:19
processIsolation=true is a workaround, you need to try with remove processIsolation

Warm regards,

Abdul Malik Ikhsan

Pada 3 Jul 2016, pukul 23.27, Thijmen Stavenuiter <notifications@github.com> menulis:

> processIsolation=true

**Comment by damianoporta** [comment] 2016-07-11 16:39
Same here! processIsolation=true is a workaround. But it is very slow. Do we still need it ?

**Comment by samsonasik** [comment] 2016-08-04 18:31
this issue still happen in php 7.0.8 and xdebug 2.4.1

**Comment by dmeziere** [comment] 2016-08-13 15:47
Same problem here. Coverage only marks executed code and ignores not-executed one. Using process isolation works, but take 40 min instead of 5 min, and a lot of failures that did not append without process isolation (must come from the way i developed my tests). This isn't usable. Ubuntu 16.04, PHP 7.0.8, Xdebug 2.4.0, Phpunit 5.5.0.

**Comment by spronkey** [comment] 2016-08-16 03:05
Yep, same problem here. Fails even with processIsolation=true on 7.0.8 with Xdebug 2.4.0 and 2.4.1 on Mac OS X (via Homebrew). Shows executed lines just fine, white background on any non-executed line, always 100%.

**Comment by cosmok** [comment] 2016-08-25 05:17
White/no background instead of red background for code that is not covered. Confirmed. Goes away when using --process-isolation (5x slower)
PHP 7.0.9-1+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.9-1+deb.sury.org~trusty+1, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans

phpunit --version
PHPUnit 5.5.3 by Sebastian Bergmann and contributors.

**Comment by garex** [comment] 2016-09-02 09:46
Seems like php7+xdebug2.4 is the source.

Same on latest phpunit and ancient:

* Generated by php-code-coverage 4.0.1 using PHP 7.0.9 with Xdebug 2.4.0 and PHPUnit 5.5.4 at Fri Sep 2 12:43:16 MSK 2016.
* Generated by PHP_CodeCoverage 1.2.18 using PHP 7.0.9 and PHPUnit 3.7.38 at Fri Sep 2 12:45:25 MSK 2016.

```
PHP 7.0.9 (cli) (built: Jul 20 2016 18:08:08) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.9, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans

```

**Comment by samsonasik** [comment] 2016-09-02 09:48
no, see @derickr comment above: https://github.com/sebastianbergmann/php-code-coverage/issues/411#issuecomment-184325369

**Comment by garex** [comment] 2016-09-02 09:57
@samsonasik Why then results same under latest and ancient phpunit versions?

**Comment by garex** [comment] 2016-09-02 10:39
It's an xdebug issue.

* Runtime: PHPDBG 7.0.10 works ok
* Runtime: PHP 7.0.10 with Xdebug 2.4.1 gives completely wrong results

I'm switching to PHPDBG. It's also much faster.

**Comment by derickr** [comment] 2016-09-02 10:53
@garex - If you can reproduce this in a *small* case, then I am happy to look at it.

Until it's been diagnosed, you can't say what causes it. That's called jumping to solutions. 

Be aware that PHPDBG does not do the same things that Xdebug does: https://translate.google.co.uk/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Feltonminetto.net%2Fpost%2F2016-08-30-gerando-phpunit-code-coverage-with-phpdbg%2F&edit-text=&act=url (Sorry, original in Spanish only right now). For example, I don't think it does dead code analysis or other tricks to filter out redundant bits.

**Comment by garex** [comment] 2016-09-02 10:57
@derickr 

> For example, I don't think it does dead code analysis or other tricks to filter out redundant bits.

By dead code you mean yellow? Yes, it marks it by red color (not executed). But at least it shows it correcltly.

**Comment by garex** [comment] 2016-09-02 11:32
@derickr What do you need to prove it? Docker image or just simplest github repo?

**Comment by samsonasik** [comment] 2016-09-02 15:43
I've created repo https://github.com/samsonasik/highlight based @mauryfs comment above at https://github.com/sebastianbergmann/php-code-coverage/issues/411#issuecomment-218535134

**Comment by garex** [comment] 2016-09-02 17:30
@samsonasik At your example you used not latest versions as you start `phpunit`, that globally installed and not from your's `vendor/bin/phpunit`

* Generated by PHP_CodeCoverage 2.0.16 using PHP 7.0.8 and PHPUnit 4.6.4 at Fri Sep 2 22:38:32 WIB 2016.

I used locally `vendor/bin/phpunit` and under php+xdebug both HighlightBad.php.inc and HighlightGood.php.inc was green.

But under PHPDBG they both orange (67%).

**Comment by samsonasik** [comment] 2016-09-02 19:11
@garex updated

**Comment by derickr** [comment] 2016-09-05 09:47
There is quite too much code to analyse in that repository, @garex. It would mean debugging all of phpunit too. The *simplest* case would be just the source files for the classes, the test case that runs it (out of phpunit) and the xdebug_start/stop/get_coverage calls to go with it. I realize that is a pain to get to, but right now, as I don't have a lot of spare time, **I** don't have the time to do that. If you do have the time, that would be great!

**Comment by samsonasik** [comment] 2016-09-05 10:33
@derickr if what you mean is the repository I mentioned ( https://github.com/samsonasik/highlight ), then the main sources files are just `core/highlight` ( 3 classes ) , the `build/` folder is a generated files that I should not commited. I can remove the `build` folder if it help further analysis.

**Comment by garex** [comment] 2016-09-05 10:34
@samsonasik Pls create just one class and another file, that calls directly xdebug_* functions. Without any composer.json.

Then to prove it -- run through travis on matrix like php 5.4, 5.5, 5.6 and 7. To prove that it will bugs on 7.

**Comment by samsonasik** [comment] 2016-09-05 13:20
@garex with just one class, it got expected result, the issue on highlight is when registering a custom autoloader as @mauryfs mentioned. I don't have idea about  xdebug_* functions you meant. 

btw, I've enable the travis and this is the travis result:
- *for php 5.6* : https://travis-ci.org/samsonasik/highlight/jobs/157633998 ( expected )
- *for php  7*   : https://travis-ci.org/samsonasik/highlight/jobs/157633999  ( not expected )

**Comment by MatthiasKuehneEllerhold** [comment] 2016-09-05 13:22
Just to clarify: the issue happens with the standard composer autoloader too.

**Comment by garex** [comment] 2016-09-05 13:34
@samsonasik as you see here only @derickr can actually fix xdebug part. But also you see, that he is very busy man. So to help him maximmally — isolate the issue and show it in virgin state without any phpunit.

As we know it's a xdebug+php7+autoload stuff. So just show us this! Let it be some simple project with composer.json with autoload and test.php file, where you create some class, do nothing and then get code coverage info.

Docs are here: https://xdebug.org/docs/code_coverage

In travis tests with bad coverage should fail when good expected coverage should not fail.

**Comment by derickr** [comment] 2016-09-11 10:58
I might have found an issue, where due to a bug the wrong function name was generated. Can you try the following branch:  https://github.com/derickr/xdebug/tree/issue1331-code-coverage-segfault ?

**Comment by samsonasik** [comment] 2016-09-11 11:15
@derickr I tried your branch and the detail of `HighlightBad` and `HighlightGood` still got 100% coverage:
```
Apples-MBP:highlight samsonasik$ php -v
PHP 7.0.10 (cli) (built: Aug 31 2016 10:25:51) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.10, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.0-dev, Copyright (c) 2002-2016, by Derick Rethans

Apples-MBP:highlight samsonasik$ vendor/bin/phpunit --coverage-text
PHPUnit 5.4.7 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

Time: 65 ms, Memory: 4.00MB

OK (2 tests, 2 assertions)

Generating code coverage report in HTML format ... done


Code Coverage Report:  
  2016-09-11 18:11:30  
                       
 Summary:              
  Classes: 66.67% (2/3)
  Methods: 80.00% (4/5)
  Lines:   75.00% (6/8)

HighlightBad
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% (  3/  3)
HighlightGood
  Methods: 100.00% ( 2/ 2)   Lines: 100.00% (  3/  3)
```
![high](https://cloud.githubusercontent.com/assets/459648/18416891/afcac15e-784b-11e6-877f-fb7c41729410.png)

**Comment by romainneutron** [comment] 2016-10-13 11:21
@derickr I Tried you branch without success

**Comment by romainneutron** [comment] 2016-10-16 13:55
Hello,

I've tracked down the issue to Xdebug: in some condition the executable lines are not fully returned, resulting in the same amount of executed line and executable line.

It's pretty difficult to reproduce the issue in a very small amount of code, here's what I've seen using var_dump in code-coverage own code:

In some case (when it works as expected), here's the kind of code coverage data reported by Xdebug:
```
{
    "36": [
        "Bundle\\MyBundle\\Tests\\Controller\\Debug\\MyAccountControllerTest::testAccountIndex"
    ],
    "37": null,
    "49": [],
    "51": [],
    "52": [],
    "56": [],
    "58": null,
    "70": [],
    "71": null,
    "83": [],
    "84": null,
    "101": [],
    "102": [],
    "105": [],
    "107": [],
    "108": [],
    "110": [],
    "111": [],
    "112": [],
    "113": [],
    "114": [],
    "115": [],
    "116": [],
    "118": null
}
```

However, when the same test is run in the test suite, here's the code coverage data reported by xdebug:

```
array(2) {
  [36] =>
  array(1) {
    [0] =>
    string(87) "Bundle\MyBundle\Tests\Controller\Debug\MyAccountControllerTest::testAccountIndex"
  }
  [37] =>
  NULL
}
```

I hope it would help @derickr to solve the issue. In the meantime, I'm continuing to try to find a small reproducer

**Comment by garex** [comment] 2016-10-16 14:08
@romainneutron 

> the same test is run in the test suite

What about some 'process isolation'? Could it be the issue?

**Comment by romainneutron** [comment] 2016-10-16 14:15
No process isolation in my case

**Comment by romainneutron** [comment] 2016-10-17 08:40
Reported to Xdebug tracker at https://bugs.xdebug.org/view.php?id=1355

**Comment by samsonasik** [comment] 2016-10-17 08:57
its already reported before: https://bugs.xdebug.org/view.php?id=1224 , just need to re-open the issue

**Comment by derickr** [comment] 2016-10-17 08:59
Please don't file issues or reopen issues until you have a short reproducible case with which I can reproduce it.

**Comment by romainneutron** [comment] 2016-10-17 09:03
@derickr I'd love to get the 10lines reproducer you wish, however it's not trivial at all. I've spent my sunday afternoon to get it without success, just for you. 
What I found is that the issue is not in PHP code coverage but in Xdebug. Where ? In Which condition? I still don't know. But I'd rather enjoy a cooperation here with you instead of "please don't report anything that I can not reproduce easily". Sounds a bit harsh and disrespectful for people trying to get the issue fixed.

We could find another way: Let's create a project that reproduce the issue, let's remove code until we get the smaller code that reproduce it.

Have a good monday !

**Comment by derickr** [comment] 2016-10-17 10:23
Although I'd like to fix this, I don't know where the problem is either. If I can't reproduce it, I can't fix it. From my point of view, it mostly sounds like an "it doesn't work" bug report.

If you can provide a VM and a few lines that I need to execute to reproduce the problem (with the latest Xdebug's from GitHub), then I can have a play around.

Without a reproducible case, I can't do anything but guess. And guessing never gets things fixed.

```
export USE_ZEND_ALLOC=0
```

Install valgrind.

**Comment by samsonasik** [comment] 2016-10-17 10:38
sample reproducable case like my repo above: https://github.com/samsonasik/highlight https://github.com/sebastianbergmann/php-code-coverage/issues/411#issuecomment-246174968

**Comment by romainneutron** [comment] 2016-10-17 20:46
Sounds @samsonasik provided the reproducer you needed @derickr

**Comment by lordelph** [comment] 2016-11-03 12:13
Nice work @samsonasik on that reproducable case. FWIW, I was able to reproduce the problem with that repo using php-code-coverage 4.0.0 / PHP 7.0.12 / Xdebug 2.4.1 / PHPUnit 5.4.7

**Comment by o5** [comment] 2016-11-15 13:42
Same issue here :/
```
PHP 7.0.12-1+deb.sury.org~xenial+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.12-1+deb.sury.org~xenial+1, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
PHPUnit 5.6.2 by Sebastian Bergmann and contributors.
```

Used `processIsolation=true` as workaround, but very slow from now. 

`48 tests, 98 assertions` 
- with `processIsolation=false` **Time: 3.16 seconds, Memory: 22.00MB**
- with `processIsolation=true` **Time: 14.64 seconds, Memory: 6.00MB**

**Comment by deviantintegral** [comment] 2016-11-28 21:40
In some spot testing, I'm getting different results on a linux installation compared to OS X installed via homebrew.

Homebrew (I just forced it down to 7.0.12 to match). The HTML shows unexecuted code as executed:

```
PHP 7.0.12 (cli) (built: Nov 28 2016 16:34:11) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.12, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```

PHP in the official Drupal docker container, with the same code, shows the report properly:

```
PHP 7.0.12 (cli) (built: Oct 21 2016 23:27:05) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.12, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```

**Comment by Jean85** [comment] 2016-11-29 08:25
Everything seems the same, except for the build... Maybe the PHP build on OS X is somehow botched?

**Comment by MatthiasKuehneEllerhold** [comment] 2016-11-29 08:55
@Jean85 Yeah maybe, but we've seen plenty of reports (in this issue!) with native linux PHP environments that are failing.

**Comment by sebastianbergmann** [comment] 2016-11-29 10:30
Sorry, but this ticket is a nightmare as multiple issues are discussed.

I have moved the problem that @ramsey reported to a #488.

I close this ticket and lock its conversation now. If any of the other issues discussed here still exist with the current stable version of PHPUnit and php-code-coverage then please open a new ticket. Sorry for any inconvenience this may cause.

**Closed by sebastianbergmann** 2016-11-29 10:30 UTC

**Comment by eostis** [comment] 2017-05-16 07:57
Same issue of 100% code coverage on partially tested files **_solved by upgrading xdebug_**.

Before:
```
Xdebug installed: 2.4.0
Server API: Command Line Interface
Windows: no
Zend Server: no
PHP Version: 7.0.12-1
Zend API nr: 320151012
PHP API nr: 20151012
Debug Build: no
Thread Safe Build: no
Configuration File Path: /etc/php/7.0/cli
Configuration File: /etc/php/7.0/cli/php.ini
Extensions directory: /usr/lib/php/20151012
```

After:
```
Xdebug installed: 2.5.4
Server API: Command Line Interface
Windows: no
Zend Server: no
PHP Version: 7.0.12-1
Zend API nr: 320151012
PHP API nr: 20151012
Debug Build: no
Thread Safe Build: no
Configuration File Path: /etc/php/7.0/cli
Configuration File: /etc/php/7.0/cli/php.ini
Extensions directory: /usr/lib/php/20151012

```
