### ISSUE TITLE
Class declaration line is marked as uncovered in PHPUnit 9.3

### ISSUE THREAD

**Issue by emodric** [sebastianbergmann/php-code-coverage#774] opened 2020-07-03 11:19 UTC
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.3-dev
| PHP version         | 7.4
| Installation Method | Composer

#### Summary

For some classes, PHPUnit marks the class declaration line (`final class Foo`) as uncovered.

#### Current behavior

![image](https://user-images.githubusercontent.com/362286/86464426-c2f26700-bd2f-11ea-822f-fe58e96dd41b.png)

#### How to reproduce

Not really sure how to reproduce aside from upgrading from PHPUnit 9.2 to 9.3 and migrating coverage config.

#### Expected behavior

To behave as PHPUnit 9.2

![image](https://user-images.githubusercontent.com/362286/86464378-b0782d80-bd2f-11ea-96fa-c4af49a30bc3.png)

**Comment by sebastianbergmann** [comment] 2020-07-03 12:08
@dvdoug Could this be related to your refactorings / improvements?

**Comment by dvdoug** [comment] 2020-07-03 12:55
@emodric, which coverage driver are you using? And what value do you have for `processUncoveredFiles`? If the answers are "Xdebug" and "true" then I think this is https://bugs.xdebug.org/view.php?id=1798

**Comment by emodric** [comment] 2020-07-03 13:00
I use Xdebug 2.9.6 and I do not have `processUncoveredFiles` configured (I don't know the default value).

Note that I only upgraded `phpunit/phpunit` from 9.2 to 9.3 and with it `phpunit/php-code-coverage` from 8.0.2 to `dev-master`. Is this something that manifests only on `dev-master` of `phpunit/php-code-coverage` (due to Xdebug issue you linked)?

**Comment by dvdoug** [comment] 2020-07-03 13:06
@emodric would you mind deleting `var/cache` and try running your test suite again? I'm curious if that will act as a workaround for you.

The linked Xdebug bug has been there a while I think, but released versions of php-code-coverage seem to accidentally work around it

**Comment by emodric** [comment] 2020-07-03 13:10
I'm not running this in Symfony context (i.e. no Symfony app, no `var/cache/`, no container). This is a pure unit tests run, no integration testing.

**Comment by emodric** [comment] 2020-07-03 13:17
To make it clearer, I'm aware that screenshots show that I'm using Symfony controllers to test, that indeed is a run in Symfony context.

BUT, this also happens in a separate run not related to Symfony. I only happened to pick a first class I ran into, which was a Symfony controller :)

**Comment by emodric** [comment] 2020-07-03 13:38
@dvdoug Clearing Symfony cache for integration tests definitely helped. But as I said in my other comment, this happens in a separate run not related to Symfony, so there's no Symfony cache to clear.

**Comment by dvdoug** [comment] 2020-07-03 13:45
@emodric Thanks for confirming. "Manually clear the Symfony cache before every test run" is obviously a terrible workaround, but that does confirm the Xdebug issue affects `extends` as well as `implements`.

@sebastianbergmann The issue is that the class declaration is (sometimes) initially marked as an executable line by Xdebug, but then each test run only returns lines inside methods as actually executed. I'll see what I can do on the php-code-coverage side to mitigate.

**Closed** 2020-07-04 05:27 UTC

**Comment by mvorisek** [comment] 2022-11-05 09:44
related with https://bugs.xdebug.org/view.php?id=1798
