### ISSUE TITLE
Importing a function breaks code coverage

### ISSUE THREAD

**Issue by natebrunette** [sebastianbergmann/php-code-coverage#506] opened 2017-02-01 06:06 UTC
Using the `use function` syntax shows all code in the class as unexecutable and will not display coverage.

```
PHP 7.1.1 (cli) (built: Jan 21 2017 13:36:56) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```

**Comment by sebastianbergmann** [comment] 2017-02-01 06:14
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by natebrunette** [comment] 2017-02-02 17:19
@sebastianbergmann https://github.com/natebrunette/codecoverage

**Comment by MadEgg** [comment] 2017-02-25 08:24
I experienced the same issue. I can reproduce it like this: 
``<?php
namespace Test;

use function printf;

function foo() {
    return "bar";
}

class Test extends \PHPUnit\Framework\TestCase {
    function testTest() {}
}
``

Save this file as Test.php and run

``
phpunit --whitelist . . --coverage-html coverage
``

Removing the 'use function printf' makes he function Test\foo show up in the output, with it in place Foo\bar is not listed in the overview and in the code not marked as either executed or not executed.

**Comment by Netmosfera** [comment] 2017-02-27 07:49
same here, using phpunit 6
with the inline qualified name `\path\to\func()` everything works fine, with `use function \path\to\func;` i get empty code coverage

**Comment by sebastianbergmann** [comment] 2017-02-27 08:35
I cannot reproduce this:

#### `src/Foo.php`
```php
<?php
namespace vendor;

use printf;

class Foo
{
    public function bar()
    {
        return true;
    }
}
```

#### `tests/FooTest.php`
```php
<?php
namespace vendor;

use PHPUnit\Framework\TestCase;

class FooTest extends TestCase
{
    public function testOne()
    {
        $foo = new Foo;
        
        $this->assertTrue($foo->bar());
    }
}
```

#### `phpunit.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/6.0/phpunit.xsd"
         bootstrap="src/Foo.php"
         verbose="true">
    <testsuite>
        <directory suffix="Test.php">tests</directory>
    </testsuite>

    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">src</directory>
        </whitelist>
    </filter>
</phpunit>
```

#### Screenshot
![screenshot from 2017-02-27 09-34-56](https://cloud.githubusercontent.com/assets/25218/23354157/1f5225a4-fcd0-11e6-8db6-5e576404287f.png)

**Comment by MadEgg** [comment] 2017-02-27 08:45
That is most likely because you use

```
use printf;
```

rather than

```
use function printf;
```

If I change that line in your example, I can reproduce the problem.

**Comment by sebastianbergmann** [comment] 2017-02-27 09:37
All lines in `Foo.php` are ignored by https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/CodeCoverage.php#L836 because the expression in https://github.com/sebastianbergmann/php-code-coverage/blob/master/src/CodeCoverage.php#L832 wrongly evaluates to `true` because `$classes[$token->getName()]['methods']` is empty when it should not be.

**Comment by sebastianbergmann** [comment] 2017-02-27 09:43
The root cause is https://github.com/sebastianbergmann/php-token-stream/issues/64

**Closed** 2017-02-27 10:18 UTC
Labels: bug
