### ISSUE TITLE
Return statement in anonymous function breaks coverage for the rest of the method

### ISSUE THREAD

**Issue by jtreurniet** [sebastianbergmann/php-code-coverage#548] opened 2017-08-25 02:33 UTC
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 5.2.2
| PHP version               | 7.1.7
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.5.5
| Installation Method       | Composer 
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 6.3.0

When, inside a class method (**not** in a regular function), I define an anonymous function which returns a value, the remainder of the method is not considered at all in the code coverage report. It appears to think that the return statement of the anonymous function is somehow the end of the method, as illustrated below:

![screen shot 2017-08-24 at 22 29 30-fullpage](https://user-images.githubusercontent.com/30029909/29697265-18401ae0-891c-11e7-992e-3ad97ce31568.png)

Also note that the table at the top states that the `returnTrue` method has 0 lines, which is clearly incorrect.

**Comment by stof** [comment] 2017-09-04 09:54
I confirm the issue. I'm seeing the same.

Lines of the method which are before the definition of the anonymous function are reported fine.

**Comment by sebastianbergmann** [comment] 2017-11-27 03:47
Please open a new ticket in case this was not a duplicate of #424 (and is not fixed by 0c3e0ad340b96cf38d4807a73d517234646e47bf).

**Closed by sebastianbergmann** 2017-11-27 03:47 UTC
Labels: bug
