### ISSUE TITLE
Code Coverage: coverage-html ignoring whole blocks of code

### ISSUE THREAD

**Issue by jaccoTopVintage** [sebastianbergmann/php-code-coverage#450] opened 2016-06-13 13:15 UTC
For our project, we have configured (local) code coverage reports using the coverage-html writer.

To our surprise, we found that some methods are marked 100% covered, **but** when looking at the method in question, _no test appears to ever have touched the code block_:

![codecoverage_snip](https://cloud.githubusercontent.com/assets/17593826/16008734/9c3195b4-3179-11e6-93e3-fc99b9219531.jpg)

I've tried all possible combinations for `addUncoveredFilesFromWhitelist` and `processUncoveredFilesFromWhitelist` (as described [on stackoverflow](http://stackoverflow.com/questions/29041254/phpunit-coverage-what-is-the-difference-between-adduncoveredfilesfromwhitelist#29042391)), but those settings, unfortunately, do not seem to affect the issue described.

a. Is this caused by misconfiguration on our side?
b. Is this a known bug?
c. something else?

Our big question is:
**How can we solve this issue?**

<br><br>
<sup>
**Attached:** Our phpunit.xml file

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="tests/bootstrap.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false">
    <testsuites>
        <testsuite name="Application Test Suite">
            <directory>./tests/</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="false">
            <directory suffix=".php">app/</directory>
        </whitelist>
    </filter>
    <logging>
        <log type="coverage-html" target="report" lowUpperBound="45" highLowerBound="90"/>
    </logging>
</phpunit>
```

</sup>

**Comment by GrahamCampbell** [comment] 2016-06-13 14:38
Does it work on the current version?

**Comment by GrahamCampbell** [comment] 2016-06-13 14:38
PHP 7.0.7, PHPUnit 5.4.4.

**Comment by jaccoTopVintage** [comment] 2016-06-13 17:13
This is with PHPUnit v5.2.12, PHP_CodeCoverage v3.3.0 (both updated using composer ("phpunit/phpunit": "^5.0") minutes before the screenshot was made) and PHP v7.0.4.

We have the same issue on several different (Windows 10) machines, with several different versions of Xdebug , where the Xdebug  version is as advised by the [Xdebug wizard](https://xdebug.org/wizard.php) for the machine in question.

**Comment by GrahamCampbell** [comment] 2016-06-13 17:14
> This is with PHPUnit v5.2.12, PHP_CodeCoverage v3.3.0 (both updated using composer ("phpunit/phpunit": "^5.0") minutes before the screenshot was made) and PHP v7.0.4.

Right, but that's not supported anymore. Please try with the newest version.

**Comment by jaccoTopVintage** [comment] 2016-06-14 08:09
Ok, Updated everything to the latest version:

* **PHP** 7.0.7 (VC14 x64 Thread Safe (2016-May-25 23:02:16))
* **XDebug** 2.4.0 (php_xdebug-2.4.0-7.0-vc14-x86_64.dll)
* **PHPUnit** 5.4.4
* **php-code-coverage** 4.0.0

And we still got the same issue:

![phpunit_screenshot_snip](https://cloud.githubusercontent.com/assets/17593826/16035529/f002a41e-3217-11e6-9b8f-ba3403cc7f29.jpg)

Anything else we can do to track down the source of this issue?

**Comment by jaccoTopVintage** [comment] 2016-06-14 08:15
It looks like this may be the same issue as: [#422](https://github.com/sebastianbergmann/php-code-coverage/issues/422)

**Comment by ramsey** [comment] 2016-11-24 00:07
And maybe a duplicate of #411.

**Comment by sebastianbergmann** [comment] 2017-11-26 15:52
Please open a new ticket in case this is not a duplicate of #411 or #422.

**Closed by sebastianbergmann** 2017-11-26 15:52 UTC
