### ISSUE TITLE
PHPUnit coverage - Interfaces always 100% covers.

### ISSUE THREAD

**Issue by GabrielDeveloper** [sebastianbergmann/php-code-coverage#436] opened 2016-05-10 19:23 UTC
I'm implementing a interface in a class but some methods of interface implemented weren't tested nevertheless my interface have 100% coverage (the interface, not the class).

If has a test just a method that should be implemented of interface, the phpunit covers 100% of interface, even if haven't test of all interface's methods.

Can someone help me?

Sorry my ignorance!

**Comment by sebastianbergmann** [comment] 2016-05-10 19:26
Duplicate of #432

**Closed by sebastianbergmann** 2016-05-10 19:26 UTC
