### ISSUE TITLE
"elseif" being marked as uncovered

### ISSUE THREAD

**Issue by twifty** [sebastianbergmann/php-code-coverage#482] opened 2016-11-16 20:28 UTC
This may be an Xdebug problem, but posting it here just in case.

Take the following code
````php
$val = 2.5;
if (is_string($val) { //<-- Line 2
   // do sth
} elseif ($val instanceof \Traversable) { //<-- Line 4
  //
} else if (is_object($val)) { //<-- Line 6
  //
} else {
  //
}
````
All lines are marked as covered, except for line 4. For some reason, writing `elseif` as a single word causes a false negative.

PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans

**Comment by sebastianbergmann** [comment] 2016-11-17 05:29
@derickr: This looks like an Xdebug issue. Can you confirm?

**Comment by derickr** [comment] 2016-11-22 11:21
Not really, with this small example. VLD produces:

```
compiled vars:  !0 = $val
line     #* E I O op                           fetch          ext  return  operands
-------------------------------------------------------------------------------------
   1     0  E >   EXT_STMT                                                 
         1        ASSIGN                                                   !0, 2.5
   2     2        EXT_STMT                                                 
         3        TYPE_CHECK                                    6  ~2      !0
         4      > JMPNZ                                                    ~2, ->9
   4     5    >   INSTANCEOF                                       ~2      !0, 'Traversable'
         6      > JMPNZ                                                    ~2, ->9
   6     7    >   EXT_STMT                                                 
         8        TYPE_CHECK                                    8  ~1      !0
  11     9    > > RETURN                                                   1
```

And the ```JMPNZ``` opcode is overloaded, so this should be caught unless the branch does not get hit. 

The original reproduce case is however incomplete, so I can't attempt to reproduce the whole problem.

**Comment by twifty** [comment] 2016-11-22 14:38
I just tried to reproduce the problem, but failed. So looked through my code trying to find the original source, but I've heavily refactored it since. All I can do now is close this issue and report back if I see it again.

**Comment by twifty** [comment] 2016-11-23 14:46
Here is a reproduction
````php
    public function whatAmI($var)
    {
        if (is_scalar($var)) { // <-- Hit
            return 'string';
        }
        
        elseif ($var instanceof \stdClass) { // <-- Miss
            return '\stdClass'; // <-- Hit
        }
        
        return 'dunno!';
    }


    public function testWhatIsIt()
    {
        $object->whatAmI(new \stdClass);
    }
````
The example should produce 3 hits, where in fact the `elseif` line is missed. Changing it to `else if` produces the correct results.

**Comment by derickr** [comment] 2016-11-23 17:04
That's not a full reproducible case. Please provide real test file, and the *full* PHP file.

And have you tried this with Xdebug 2.4.1 (and 2.5.0RC1) first too?

**Comment by tarlepp** [comment] 2016-12-19 21:39
I have this same issue with ```elseif``` see here https://coveralls.io/builds/9348780/source?filename=src%2FApp%2FEventListener%2FExceptionListener.php#L70

If I change that to ```else if``` that line is covered.

**Comment by tarlepp** [comment] 2016-12-19 22:53
And another thing I noticed that eg. following

```php
} elseif ($exception instanceof DBALException
    || $exception instanceof ORMException
) { // Database errors
```

won't catch the ```} elseif ($exception instanceof DBALException``` line at all, but next lines are covered... So only solution for this was to make that one liner...

POC for that here (and yes test covers both of those cases): https://coveralls.io/builds/9350371/source?filename=src%2FApp%2FEventListener%2FExceptionListener.php#L123

**Comment by tarlepp** [comment] 2016-12-29 21:55
any updates on this?

**Comment by tflori** [comment] 2017-01-12 07:41
:+1:  I have exactly the same problem - solved with an `else if` for now.

@derickr I'm using xdebug 2.4.1 and it does not stop in the line `} elseif ($o instanceof \PDO) {` 

```php
<?php

function whatAmI($var) {
    if (is_scalar($var)) { // <-- Hit
        return 'string';
    } elseif ($var instanceof \stdClass) { // <-- Miss
        return '\stdClass'; // <-- Hit
    }
    return 'dunno!';
}

whatAmI(new \stdClass);
```

**Comment by derickr** [comment] 2017-01-12 11:07
@tarlepp - no, as https://github.com/tarlepp/symfony-backend/blob/master/tests/AppBundle/EventListener/ExceptionListenerTest.php gives a 404.

@tflori - Code coverage never "stops" on anything - and you didn't say which PHP version you were using.

**Comment by tflori** [comment] 2017-01-12 11:26
@derickr code coverage is using xdebug. xdebug does not stop in the line. I'm using php 7.0.14 on arch linux with linux kernel 4.4.

**Comment by tarlepp** [comment] 2017-01-17 19:38
@derickr oh sorry I have changed that structure already a bit correct link below:

https://github.com/tarlepp/symfony-backend/blob/master/tests/AppBundle/unit/EventListener/ExceptionListenerTest.php

**Comment by tarlepp** [comment] 2017-01-17 19:45
@derickr and if you're asking next the versions of that run, just see https://travis-ci.org/tarlepp/symfony-backend/builds/185302904 I'm running that with PHP 7.0.x and 7.1.x detailed information you can see on those TravisCI builds

**Comment by tarlepp** [comment] 2017-01-23 19:19
any updates on this?

**Comment by tarlepp** [comment] 2017-01-28 14:52
any updates on this?

**Comment by sebastianbergmann** [comment] 2017-01-28 15:52
@tarlepp You have yet to provide a minimal, self-contained, reproducing example for @derickr to investigate. Spamming "any updates on this" is not going to help.

**Comment by sebastianbergmann** [comment] 2017-01-28 16:42
I am closing this is as I do not think this is an issue in this component.

**Closed by sebastianbergmann** 2017-01-28 16:42 UTC
Labels: xdebug

**Comment by tarlepp** [comment] 2017-01-29 11:40
@sebastianbergmann we have provided multiple examples, but I'll create another repo to prove this.

**Comment by tflori** [comment] 2017-01-29 11:57
@tarlepp I've created an issue on bugs.xdebug.org with an example..

**Comment by tarlepp** [comment] 2017-01-29 12:00
and I created repo to prove this too https://github.com/tarlepp/phpunit-coverage-poc

**Comment by tflori** [comment] 2017-01-29 13:30
solved in commit https://github.com/xdebug/xdebug/commit/aa1f3857c396f5679d15dbe0d110160a6198fcac

**Comment by tarlepp** [comment] 2017-01-29 14:24
@sebastianbergmann it seems that now this is fixed, so it seems that "spammining" this issue was the correct way after all.

**Comment by derickr** [comment] 2017-01-29 15:08
@tarlepp It isn't. The best and nicest way to get things fixed is small reproducible cases like the one that was filed for this in the Xdebug bug tracker. Cases like that are *vital* for our sanity, and have a much Betsy chance to get fixed sooner  that issues requiring any of us to delve trough lots of unnecessary code. For most code coverage issues that means getting of everything PHPUnit or PHP Code Coverage.
