### ISSUE TITLE
Test failed with PHPUnit 7.2.1

### ISSUE THREAD

**Issue by remicollet** [sebastianbergmann/php-code-coverage#624] opened 2018-06-01 07:36 UTC
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 6.0.6
| PHP version               | 7.1.8 / 7.2.6
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.7.0alpha1
| Installation Method       | other ;)
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 7.2.1

Related to https://github.com/sebastianbergmann/phpunit/commit/b06a7e6cad0bc103b835381e4d8dafbe013df9b6

```
There were 2 failures:

1) SebastianBergmann\CodeCoverage\CodeCoverageTest::testCollect
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'BankAccountTest::testBalanceIsInitiallyZero' => Array (
         'size' => 'unknown'
-        'status' => null
+        'status' => -1
     )
     'BankAccountTest::testBalanceCannotBecomeNegative' => Array (
         'size' => 'unknown'
-        'status' => null
+        'status' => -1
     )
     'BankAccountTest::testBalanceCannotBecomeNegative2' => Array (
         'size' => 'unknown'
-        'status' => null
+        'status' => -1
     )
     'BankAccountTest::testDepositWithdrawMoney' => Array (
         'size' => 'unknown'
-        'status' => null
+        'status' => -1
     )
 )

/dev/shm/BUILD/php-code-coverage-1661926cfa5be825d4f96f89dfac46dc4a19afa8/tests/tests/CodeCoverageTest.php:232

2) SebastianBergmann\CodeCoverage\Report\Html\HTMLTest::testForBankAccountTest
BankAccount.php.html not match
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
...
```

**Comment by sebastianbergmann** [comment] 2018-06-01 07:38
Duplicate of #623.

**Closed by sebastianbergmann** 2018-06-01 07:38 UTC
