### ISSUE TITLE
Magic bug, line is being marked as uncovered in the middle of the code.

### ISSUE THREAD

**Issue by olegserov** [sebastianbergmann/php-code-coverage#406] opened 2015-11-29 21:15 UTC
Please, take a look on this screen shot: https://www.dropbox.com/s/x4316ce9xfq1119/Screenshot%202015-11-29%2016.07.34.png?dl=0

The line 228 is marked as incomplete. 
1. The file is covered 100%. 
2. Each method is covered separately via "@ covers".
3. If you add newlines before line 228 the uncovered line stays in the same place, sometimes it moves up or down for a couple of lines.
4. I cannot provide "pure" test case, due the fact that this tests are integrated into the project and connected with DB and I cannot extract them from the project.
5. Sometimes this bug disappears.
6. It's very annoying.
7. codeCoverageIngoreStart/End does not help :(

Any clues? How do I debug this?

"Generated by PHP_CodeCoverage 3.0.1 using PHP 5.6.15 and PHPUnit 5.0.8 at Mon Nov 30 0:05:11 MSK 2015."

**Comment by sebastianbergmann** [comment] 2016-04-20 15:19
Looks like an Xdebug issue to me. @derickr?

**Comment by neomerx** [comment] 2017-05-29 10:35
I think since 7.0 or 7.1 I can see such weird behavior very often. I found usage of `phpdbg` gives accurate results
```bash
phpdbg -qrr ./vendor/bin/phpunit --coverage-text
```

**Comment by sebastianbergmann** [comment] 2017-11-26 15:56
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

**Comment by sebastianbergmann** [comment] 2017-12-07 05:12
No feedback, closing.

**Closed by sebastianbergmann** 2017-12-07 05:12 UTC
Labels: bug, waiting-for-feedback, waiting-for-reproducing-example, xdebug
