### ISSUE TITLE
Code Coverage not detected with trailing comma during array addition

### ISSUE THREAD

**Issue by marcaddeo** [sebastianbergmann/php-code-coverage#494] opened 2016-12-16 17:33 UTC
Code coverage is not being reported in this case:

![image](https://cloud.githubusercontent.com/assets/199649/21272100/c1803ca4-c38b-11e6-9720-288937c9c01e.png)

When I remove the trailing comma on the last array element it does pass:

![image](https://cloud.githubusercontent.com/assets/199649/21272137/e5ac8d80-c38b-11e6-9426-e34df65927fa.png)

**Comment by sebastianbergmann** [comment] 2016-12-16 17:34
Looks like an Xdebug / Zend Engine issue to me. @derickr?

**Comment by sebastianbergmann** [comment] 2017-11-26 15:41
@derickr ping

**Comment by sebastianbergmann** [comment] 2017-11-26 15:42
@marcaddeo Does this issue persist with up-to-date versions of PHP and Xdebug?

**Comment by sebastianbergmann** [comment] 2017-11-26 15:42
There can be many reasons why a specific line is not covered. Each of them is likely a different issue. In order to be able to reproduce *anything* and not get bogged down with details, you need to provide the following **in ONE new issue per case**.

That means:

- The exact versions of (this is what the template requires too, but more):
  - PHP
  - PHP Code Coverage
  - Xdebug
  - PHPUnit
- ```php -v``` output
- Either a ```.tar.gz``` archive or a GitHub repository with a reproduce case. With **one** file that shows the problem and **one** test case file (with the exception that sometimes, you might need **two** source files to show a problem.

This information should be filed as **one specific case per issue**.

**Comment by sebastianbergmann** [comment] 2017-12-07 05:11
No feedback, closing.

**Closed by sebastianbergmann** 2017-12-07 05:11 UTC
Labels: bug, waiting-for-feedback, waiting-for-reproducing-example, xdebug
