### ISSUE TITLE
Pure functions should be counted in the "Functions and Methods" column

### ISSUE THREAD

**Issue by Slamdunk** [sebastianbergmann/php-code-coverage#499] opened 2017-01-05 13:52 UTC
After the merge of https://github.com/sebastianbergmann/php-code-coverage/issues/432 with a source like this:
```php
// array.php
$array = array();

// function.php
function my_function()
{
}

// function_and_method.php
function my_function_2()
{
}

class my_class
{
    function my_method()
    {
    }
}
```
![cc](https://cloud.githubusercontent.com/assets/152236/21682701/4ce6736a-d356-11e6-83d2-167d8d6f1cfa.png)

I would expect for the *"Functions and Methods"* column to be `0/1` for `function.php` and to be `0/2` for `function_and_method.php`

**Comment by direvus** [comment] 2017-03-28 03:40
I think this duplicates #468

**Comment by sebastianbergmann** [comment] 2017-11-26 15:40
Duplicate of #468.

**Closed by sebastianbergmann** 2017-11-26 15:40 UTC
