### ISSUE TITLE
Classes with ignore annotation (@codeCoverageIgnore) not excluded in coverage report

### ISSUE THREAD

**Issue by pidera** [sebastianbergmann/php-code-coverage#728] opened 2020-02-12 17:51 UTC
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 8.0.0
| PHP version               | 7.4.2
| Driver                    | Xdebug 
| Xdebug version (if used)  | 2.9.0
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 9.0.0

When generating a coverage report using v8.0.0 of php-code-coverage, the annotation to ignore classes (@codeCoverageIgnore)  is not working as defined.

I have created a small repo to simulate the issue: https://github.com/pidera/coverage-annotation-bug
The class `ClassToIgnore` should be ignored in the report, but is marked as not executed.

I've run the same suite in v7.0.10, and there there is no issue.

Here you can see the difference between the two reports:

## v8.0.0

<img width="1087" alt="v8 0 0_A_Suite" src="https://user-images.githubusercontent.com/555558/74361973-19cec280-4dc8-11ea-8866-4a761f438805.png">
<img width="1085" alt="v8 0 0_B_BasicClass" src="https://user-images.githubusercontent.com/555558/74361975-1c311c80-4dc8-11ea-9ec5-a6a929017416.png">
<img width="1091" alt="v8 0 0_C_ClassToIgnore" src="https://user-images.githubusercontent.com/555558/74361984-1f2c0d00-4dc8-11ea-96c7-ce3a20fc00d6.png">

## v7.0.10

<img width="1086" alt="v7 0 10_A_Suite" src="https://user-images.githubusercontent.com/555558/74361940-0d4a6a00-4dc8-11ea-8e25-e8877f5b1f74.png">
<img width="1085" alt="v7 0 10_B_BasicClass" src="https://user-images.githubusercontent.com/555558/74361948-10455a80-4dc8-11ea-9104-3075d22a6fda.png">
<img width="1090" alt="v7 0 10_C_ClassToIgnore" src="https://user-images.githubusercontent.com/555558/74361956-12a7b480-4dc8-11ea-841a-8241945ea3a8.png">

Thanks a lot for looking into this!

**Comment by sebastianbergmann** [comment] 2020-02-12 19:52
Duplicate of #4036.

**Closed by sebastianbergmann** 2020-02-12 19:52 UTC
