### ISSUE TITLE
Line with Closure is not marked as executable

### ISSUE THREAD

**Issue by bwoebi** [sebastianbergmann/php-code-coverage#497] opened 2016-12-23 00:30 UTC
```PHP
    public function monitor(): array {
        return [
            "handler" => [get_class($this->application), $this->application instanceof Monitor ? $this->application->monitor() : null],
            "clients" => array_map(function ($client) { return $this->getInfo($client->id); }, $this->clients),
        ];
    }
```

The latter array line (`"clients" => array_map(function ($client) { return $this->getInfo($client->id); }, $this->clients),`) is marked as not executable, due to the presence of the Closure.

phpdbg properly reports it as executable, but your code is removing it in `CodeCoverage::getLinesToBeIgnored()`. (i.e. when `PHP_Token_FUNCTION` is encountered).

It's fine to remove when there is no other code on that line, but not ok to just remove it always.

**Comment by sebastianbergmann** [comment] 2017-11-27 03:48
Please open a new ticket in case this was not a duplicate of #424 (and is not fixed by 0c3e0ad340b96cf38d4807a73d517234646e47bf).

**Closed by sebastianbergmann** 2017-11-27 03:48 UTC
Labels: bug
