### ISSUE TITLE
Do not use a green bar for methods that are annotated with @codeCoverageIgnore

### ISSUE THREAD

**Issue by ghost** [sebastianbergmann/php-code-coverage#427] opened 2016-03-17 09:49 UTC
Please have a look at the attached screenshot:

![code-coverage](https://cloud.githubusercontent.com/assets/1623039/13842314/cd06ab0c-ec2d-11e5-979a-5956ed76fc02.png)

This is what I would have expected:

![code-coverage-002](https://cloud.githubusercontent.com/assets/1623039/13842337/ddb14a7a-ec2d-11e5-80b1-bcdb8ea0fbc2.png)

**Comment by sebastianbergmann** [comment] 2017-11-27 07:24
#559 is a duplicate of this.

**Closed by sebastianbergmann** 2017-11-27 07:24 UTC
