### ISSUE TITLE
method end marked as 'dead code'

### ISSUE THREAD

**Issue by N3XT0R** [sebastianbergmann/php-code-coverage#305] opened 2015-02-05 08:24 UTC
Hello, 
i have a little problem with the php code coverage tool. I am using it with phpunit and have sometimes the result, that a "}" by a method closing is declared as dead code... 

Seems like a bug... I am using the code coverage tool on a continuous integration server with debian 7 (newest release). 

![bildschirmfoto 2015-02-05 um 09 20 26](https://cloud.githubusercontent.com/assets/1297846/6056943/4ad9cf1a-ad18-11e4-9e72-a34c7aac4fce.png)

**Comment by sebastianbergmann** [comment] 2015-02-05 08:29
This is not a bug. The closing curly brace of a function or method is compiled into a `return null;` statement. If there is, for instance, an explicit unconditional `return` statement before the closing curly brace then the implicit `return null;` statement that comes from the closing curly brace is executable but dead code.

**Closed by sebastianbergmann** 2015-02-05 08:29 UTC

**Comment by N3XT0R** [comment] 2015-02-05 09:30
okay... so when i have getter methods (with individual return statements - not null), then your coverage tool will everytime declare the closing brace as dead code? In my opinion it doesnt make sense, because the closing brace is a part of the method definition. without it the php interpreter would throw a parse error exception. When i  am understanding the situation right, then a closing brace is only not dead code by your coverage tool, when it havent a individual return statement, is it right?

**Comment by whatthejeff** [comment] 2015-02-05 09:42
http://derickrethans.nl/dead-code.html has a more detailed explanation

**Comment by N3XT0R** [comment] 2015-02-05 10:00
thanks for the answer, that helps me to understand it.
