### ISSUE TITLE
Deprecated constant

### ISSUE THREAD

**Issue by Kracus** [sebastianbergmann/php-code-coverage#809] opened 2020-09-14 23:17 UTC
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 9.1.8
| PHP version               | 7.4.9
| Installation Method       | Compose
| Usage Method              | ./vendor/bin/paratest -p 4 --coverage-text --coverage-html=build/coverage
| PHPUnit version (if used) | 9.3.10

I'm getting the following error message that is just a notice but it's actually blocking my pipelines but works any way.

`Warning: Use of undefined constant T_MATCH - assumed 'T_MATCH' (this will throw an Error in a future version of PHP) in *private_path*/vendor/phpunit/php-code-coverage/src/Report/Html/Renderer/File.php on line 970`

Is someone already got this error and has a solution to solve it on my side please ?

**Comment by sebastianbergmann** [comment] 2020-09-15 05:14
Duplicate of #808.

**Closed by sebastianbergmann** 2020-09-15 05:14 UTC

**Comment by sebastianbergmann** [comment] 2020-09-15 07:59
Samw question, though, that I had on [#808](https://github.com/sebastianbergmann/php-code-coverage/issues/808#issuecomment-688626827):

> how do you trigger this warning?
