### ISSUE TITLE
HTML reports are hard to read for colorblind people

### ISSUE THREAD

**Issue by Daimona** [sebastianbergmann/php-code-coverage#698] opened 2019-09-14 09:43 UTC
| Q                         | A
| --------------------------| ---------------
| php-code-coverage version | 7.0.7
| PHP version               | 7.2.2
| Driver                    | Xdebug
| Xdebug version (if used)  | 2.6.1
| Installation Method       | Composer
| Usage Method              | PHPUnit
| PHPUnit version (if used) | 8.3.0

The HTML coverage reports use a red/green combination which is potentially very hard to read for colorblind people. This is exacerbated by cheap monitors with faint colors, where red and green are almost impossible to discern.

Note that red and green are not a problem per se (I actually like the red/green choice), their tonality is.

**Comment by sebastianbergmann** [comment] 2019-09-14 15:27
Duplicate of #556.

**Closed by sebastianbergmann** 2019-09-14 15:27 UTC
